AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: SAM app that processes CloudTrail via CloudWatch Logs and builds AMI lineage information

Resources:
  Dependencies:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: ./layer
      CompatibleRuntimes: # optional
        - python3.7

  CloudTrailToLineage:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      CodeUri: ./src
      Description: Builds a Neptune Graph from AMI & EC2 events.
      MemorySize: 512
      Timeout: 30
      Layers:
        - Ref: Dependencies
      Tracing: Active
      Events:
        LineageEvents:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: CloudTrail/LineageTrailsLogGroup
            FilterPattern: '{ $.eventName = "RunInstances" || $.eventName = "CopyImage" || $.eventName = "CreateImage" }'
      # Environment:
      #   Variables:
      #     TABLE_NAME:
      #       Ref: ResultsTable
      # Policies:
      #   - Version: '2012-10-17'
      #     Statement:
      #       - Effect: Allow
      #         Action:
      #           - 's3:GetObject'
      #         Resource: 'arn:aws:s3:::*'
      #       - Effect: Allow
      #         Action:
      #           - 'rekognition:DetectText'
      #           - 'rekognition:DetectLabels'
      #         Resource: '*'
      #       - Effect: Allow
      #         Action:
      #           - 'dynamodb:GetItem'
      #           - 'dynamodb:PutItem'
      #           - 'dynamodb:Scan'
      #           - 'dynamodb:UpdateItem'
      #         Resource:
      #           'Fn::Join':
      #             - ''
      #             - - 'arn:aws:dynamodb:'
      #               - Ref: 'AWS::Region'
      #               - ':'
      #               - Ref: 'AWS::AccountId'
      #               - ':table/'
      #               - Ref: ResultsTable
